/**
 * @packageDocumentation
 * @module api.functional.files.index_status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher'
import type { Primitive } from 'typia'

import type { FilesDto } from '../../../../presentation/files.dto'

/**
 * @controller FileStatusController.indexStatus
 * @path GET /files/:fileId/index-status
 * @accessor api.functional.files.index_status.indexStatus
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexStatus(
  connection: IConnection,
  fileId: string,
): Promise<indexStatus.Output> {
  return PlainFetcher.fetch(connection, {
    ...indexStatus.METADATA,
    template: indexStatus.METADATA.path,
    path: indexStatus.path(fileId),
  })
}
export namespace indexStatus {
  export type Output = Primitive<FilesDto.IndexStatusResponse>

  export const METADATA = {
    method: 'GET',
    path: '/files/:fileId/index-status',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const

  export const path = (fileId: string) =>
    `/files/${encodeURIComponent(fileId?.toString() ?? 'null')}/index-status`
}
