services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nxcloud-postgres
    restart: always
    environment:
      POSTGRES_DB: nxcloud_app
      POSTGRES_USER: nxcloud
      POSTGRES_PASSWORD: nxcloud123
    ports:
      - '5480:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-app.sql:ro
      - ./postgres/02-create-nextcloud-db.sql:/docker-entrypoint-initdb.d/02-create-nextcloud-db.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nxcloud']
      interval: 5s
      timeout: 5s
      retries: 5

  nextcloud:
    image: nextcloud:29-apache
    container_name: nxcloud-nextcloud
    restart: always
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin123
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nxcloud
      POSTGRES_PASSWORD: nxcloud123
    ports:
      - '8081:80'
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  nextcloud_data:
