/**
 * @packageDocumentation
 * @module api.functional.admin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as tenants from './tenants/index'
