/**
 * @packageDocumentation
 * @module api.functional.admin.tenants.users_usage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher'
import type { Primitive } from 'typia'

import type { AdminDto } from '../../../../../presentation/admin.dto'

/**
 * @controller AdminController.getUsersUsage
 * @path GET /admin/tenants/:tenantId/users-usage
 * @accessor api.functional.admin.tenants.users_usage.getUsersUsage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUsersUsage(
  connection: IConnection,
  _tenantId: string,
): Promise<getUsersUsage.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUsersUsage.METADATA,
    template: getUsersUsage.METADATA.path,
    path: getUsersUsage.path(_tenantId),
  })
}
export namespace getUsersUsage {
  export type Output = Primitive<AdminDto.UsersUsageResponse>

  export const METADATA = {
    method: 'GET',
    path: '/admin/tenants/:tenantId/users-usage',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const

  export const path = (_tenantId: string) =>
    `/admin/tenants/${encodeURIComponent(_tenantId?.toString() ?? 'null')}/users-usage`
}
