/**
 * @packageDocumentation
 * @module api.functional.files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { ChatDto } from "../../../presentation/chat.dto";

export * as index_status from "./index_status/index";

/**
 * @controller ChatController.chat
 * @path POST /files/:fileId/chat
 * @accessor api.functional.files.chat
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function chat(
  connection: IConnection,
  fileId: string,
  body: chat.Body,
): Promise<chat.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...chat.METADATA,
      template: chat.METADATA.path,
      path: chat.path(fileId),
    },
    body,
  );
}
export namespace chat {
  export type Body = Primitive<ChatDto.ChatRequest>;
  export type Output = Primitive<ChatDto.ChatResponse>;

  export const METADATA = {
    method: "POST",
    path: "/files/:fileId/chat",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (fileId: string) =>
    `/files/${encodeURIComponent(fileId?.toString() ?? "null")}/chat`;
}
