/**
 * @packageDocumentation
 * @module api.functional.tenants.files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { FormDataInput, IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher'
import type { Primitive } from 'typia'

import type { FilesDto } from '../../../../presentation/files.dto'

/**
 * @controller FilesController.upload
 * @path POST /tenants/:tenantId/files
 * @accessor api.functional.tenants.files.upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upload(
  connection: IConnection,
  _tenantId: string,
  body: upload.Body,
): Promise<upload.Output> {
  return PlainFetcher.fetch(
    connection,
    {
      ...upload.METADATA,
      template: upload.METADATA.path,
      path: upload.path(_tenantId),
    },
    body,
  )
}
export namespace upload {
  export type Body = FormDataInput<FilesDto.IUploadBody>
  export type Output = Primitive<FilesDto.FileItem>

  export const METADATA = {
    method: 'POST',
    path: '/tenants/:tenantId/files',
    request: {
      type: 'multipart/form-data',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const

  export const path = (_tenantId: string) =>
    `/tenants/${encodeURIComponent(_tenantId?.toString() ?? 'null')}/files`
}

/**
 * @controller FilesController.list
 * @path GET /tenants/:tenantId/files
 * @accessor api.functional.tenants.files.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection, _tenantId: string): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(_tenantId),
  })
}
export namespace list {
  export type Output = Primitive<Array<FilesDto.FileItem>>

  export const METADATA = {
    method: 'GET',
    path: '/tenants/:tenantId/files',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const

  export const path = (_tenantId: string) =>
    `/tenants/${encodeURIComponent(_tenantId?.toString() ?? 'null')}/files`
}
