/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

export * as tenants from "./tenants/index";
export * as files from "./files/index";
export * as auth from "./auth/index";
export * as admin from "./admin/index";

/**
 * @controller AppController.getData
 * @path GET /
 * @accessor api.functional.getData
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getData(
  connection: IConnection,
): Promise<getData.Output> {
  return PlainFetcher.fetch(connection, {
    ...getData.METADATA,
    template: getData.METADATA.path,
    path: getData.path(),
  });
}
export namespace getData {
  export type Output = Primitive<{ message: string }>;

  export const METADATA = {
    method: "GET",
    path: "/",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/";
}
