/**
 * @packageDocumentation
 * @module api.functional.auth.quota
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher'
import type { Primitive } from 'typia'

import type { AuthDto } from '../../../../presentation/auth.dto'

/**
 * @controller AuthController.getQuota
 * @path GET /auth/quota
 * @accessor api.functional.auth.quota.getQuota
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getQuota(connection: IConnection): Promise<getQuota.Output> {
  return PlainFetcher.fetch(connection, {
    ...getQuota.METADATA,
    template: getQuota.METADATA.path,
    path: getQuota.path(),
  })
}
export namespace getQuota {
  export type Output = Primitive<AuthDto.QuotaResponse>

  export const METADATA = {
    method: 'GET',
    path: '/auth/quota',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const

  export const path = () => '/auth/quota'
}
